#!/usr/bin/env php
<?php

use Timer\DailyLogger;
use Timer\Enum\Status;

include 'bootstrap.php';

$parameter = $argv[1] ?? null;

$date = (new DateTime())->format('Y-m-d');

$logger = new DailyLogger($date);
$timerManager = new Timer\Manager();

$counter = $timerManager->getCounter();
$timer = $timerManager->getTimer();

if ($parameter == 'log') {
    $log = readline('Log: ');
    $logger->log(sprintf('%s, Timer: %s ', $log, $counter->getHourFormat()));
    return;
}

match ($parameter) {
    'reset' => $counter->reset(),
    'stop' => $counter->stop(),
    'increase' => $counter->increase($argv[2] ?? null),
    default => $parameter = '',
};

$log = '';
if(file_exists(TIMER_ROOT.'/logs/'.$date.'.log')) {
    $log = file_get_contents(TIMER_ROOT.'/logs/'.$date.'.log');
}

$label = sprintf('%s | %s %s', $counter->getHourFormat(), $timer->getTimeMinutesSoFar(),  $timer->getStatus()->label());

$class = $timer->instance->is(Status::WORKING) ? 'working' : 'break';

$waybar = new Timer\WaybarRender(
    $label,
    $parameter,
    $log,
    $class
);

print $waybar->toJson() . PHP_EOL;